// src/loadingTexts.js

export const loadingTexts = [
  "Searching for your next conversation partner...",
  "Sending out connection signals...",
  "Adjusting our matching algorithm...",
  "Getting our search radar in focus...",
  "Finding your chat companion...",
  "Dusting off our matchmaking skills...",
  "Hang tight, your chat is loading...",
  "Sweeping the world for a match...",
  "Asking the stars for guidance...",
  "Consulting with our expert matchers...",
  "Searching for your ideal chat partner...",
  "Scanning for compatible frequencies...",
  "Mapping out the conversation terrain...",
  "Gathering all the friendly vibes...",
  "Tuning into social channels...",
  "Loading chat possibilities...",
  "Seeking someone to share thoughts with...",
  "Finding someone who appreciates good conversation...",
  "Matching you with someone interesting...",
  "In search of a great connection...",
  "Our algorithm is processing...",
  "Analyzing compatibility signals...",
  "Synchronizing interests...",
  "Chat detectives on the case...",
  "Locating your ideal chat partner...",
  "Preparing an engaging conversation...",
  "Setting the stage for a great chat...",
  "Surveying the user landscape...",
  "Pairing you with an intriguing individual...",
  "Getting ready for a friendly encounter...",
  "A great match is just clicks away...",
  "Drawing up conversation maps...",
  "Consulting our user archives...",
  "Combining interests in our lab...",
  "Mixing up a conversation starter...",
  "Our chat engineers are at work...",
  "Bridging personalities together...",
  "Your chat journey begins shortly...",
  "Aligning the conversation stars...",
  "Navigating to your ideal chat partner...",
  "Fine-tuning the connection...",
  "Setting sail for engaging discussions...",
  "Your match is warming up...",
  "Chat is loading, please wait...",
  "Warming up our matching engines...",
  "Making sure your match can handle your awesomeness...",
  "Preparing your chat partner for your wit...",
  "Ensuring your match appreciates good humor...",
  "Checking your future match's conversation skills...",
  "Reading the chat manual...",
  "Scrubbing the internet for your perfect match...",
  "Telling your match how interesting you are...",
  "Finding someone with similar interests...",
  "Ensuring your match enjoys good discussions...",
  "Making sure your match is pet-friendly...",
  "Prepping your match with conversation topics...",
  "Introducing your match to your interests...",
  "Finding someone who will enjoy your company...",
  "Making sure your match enjoys good conversations...",
  "Looking for someone who communicates well...",
  "Finding someone who gets your perspective...",
  "Finding someone who thinks you're interesting...",
  "Scouting for someone who enjoys a good chat...",
  "Looking for someone to share ideas with...",
  "Finding a match who likes engaging discussions...",
  "Ensuring your match can handle your unique style...",
  "Finding a partner for intellectual exchanges...",
  "Picking someone who won't judge your opinions...",
  "Locating someone who enjoys meaningful talks...",
  "Finding someone who understands your viewpoints...",
  "Making sure your match enjoys spontaneous chats...",
  "Finding a match who shares your curiosity...",
  "Checking if your match can keep up with your thoughts...",
  "Matching you with someone who appreciates your uniqueness...",
  "Finding someone who can match your energy...",
  "Preparing your match for your brilliant ideas...",
  "Locating someone who can handle your conversation style...",
  "Finding someone who enjoys intellectual discourse...",
  "Ensuring your match shares your enthusiasm...",
  "Matching you with someone who appreciates your interests...",
  "Finding someone who enjoys your company...",
];
