// src/loadingTexts.js

export const loadingTexts = [
  "Hunting for the love of your life...",
  "Sending out love signals...",
  "Adjusting Cupid's aim...",
  "Getting love radar in focus...",
  "Finding your partner in crime...",
  "Dusting off our matchmaking skills...",
  "Hang tight, love is loading...",
  "Sweeping the world for a match...",
  "Asking the stars for guidance...",
  "Consulting with the love gurus...",
  "Searching for your better half...",
  "Scanning for love frequencies...",
  "Mapping out the heart terrain...",
  "Gathering all the love vibes...",
  "Tuning into love channels...",
  "Loading romantic possibilities...",
  "Seeking someone to share memes with...",
  "Finding someone who laughs at your jokes...",
  "Matching you with someone amazing...",
  "In search of a perfect connection...",
  "Love algorithm is processing...",
  "Analyzing heart signals...",
  "Synchronizing heartbeats...",
  "Love detectives on the case...",
  "Locating your other half...",
  "Preparing a romantic adventure...",
  "Setting the stage for romance...",
  "Surveying the singles landscape...",
  "Pairing you with greatness...",
  "Unleashing Cupid's arrows...",
  "Getting ready for a love encounter...",
  "A love match is just clicks away...",
  "Drawing up love maps...",
  "Consulting the love archives...",
  "Combining hearts in the lab...",
  "Mixing up a love potion...",
  "Love engineers at work...",
  "Bridging hearts together...",
  "Your love journey begins shortly...",
  "Aligning the love stars...",
  "Navigating to your heart's desire...",
  "Fine-tuning the love connection...",
  "Setting sail for romance...",
  "Your match is warming up...",
  "Love is loading, please wait...",
  "Warming up the Cupid's arrows...",
  "Making sure your match can handle your awesomeness...",
  "Preparing your date for your epic dance moves...",
  "Ensuring your match appreciates dad jokes...",
  "Checking your future match's meme game...",
  "Reading the love manual...",
  "Scrubbing the internet for your perfect match...",
  "Telling your match how awesome you are...",
  "Picking out the best profile pics...",
  "Finding someone who loves pineapple on pizza...",
  "Ensuring your match loves the same Netflix shows...",
  "Making sure your match is cat-friendly...",
  "Teaching your match the art of sarcasm...",
  "Prepping your match with your favorite puns...",
  "Introducing your match to your quirks...",
  "Finding someone who will swipe right on your heart...",
  "Making sure your match loves karaoke nights...",
  "Looking for someone who won't ghost you...",
  "Finding someone who gets your humor...",
  "Finding someone who thinks you’re out of this world...",
  "Scouting for someone who loves to laugh...",
  "Getting someone to laugh at your jokes...",
  "Looking for someone to share your popcorn with...",
  "Finding a match who likes long walks to the fridge...",
  "Ensuring your match can handle your dance skills...",
  "Making sure your match loves cheesy movies...",
  "Finding a partner for your midnight snack raids...",
  "Picking someone who won't judge your pizza toppings...",
  "Locating someone who loves late-night talks...",
  "Finding someone who understands your inside jokes...",
  "Making sure your match loves random adventures...",
  "Ensuring your match can handle your Netflix binges...",
  "Finding a match who loves lazy Sundays...",
  "Checking if your match can handle your playlist...",
  "Matching you with someone who loves your quirks...",
  "Finding someone who can match your wit...",
  "Preparing your match for your epic comebacks...",
  "Making sure your match loves pets...",
  "Locating someone who can handle your cooking...",
  "Finding someone who loves surprise road trips...",
  "Ensuring your match loves coffee as much as you do...",
  "Matching you with someone who loves your hobbies...",
  "Finding someone who enjoys your company...",
];
